"""add company rating fields and behavioral note

Revision ID: 10a5627a5d05
Revises: 36850bcdc76d
Create Date: 2026-09-14 15:49:49.261693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a5627a5d05'
down_revision: Union[str, Sequence[str], None] = '36850bcdc76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation', sa.Column('behavioral_note', sa.String(), nullable=False, server_default=''))
    op.add_column('job_posting', sa.Column('company_rating', sa.Float(), nullable=True))
    op.add_column('job_posting', sa.Column('company_rating_source', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posting', 'company_rating_source')
    op.drop_column('job_posting', 'company_rating')
    op.drop_column('evaluation', 'behavioral_note')
    # ### end Alembic commands ###
