"""initial schema

Revision ID: 14808d7b69a2
Revises: 
Create Date: 2026-09-14 00:46:48.382479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14808d7b69a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('commute_radius_miles', sa.Integer(), nullable=False),
    sa.Column('remote_ok', sa.Boolean(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('employment_type_preference', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('key_topics', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_tier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_portal', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('detected_platform', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('qa_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_pattern', sa.String(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fit_threshold', sa.Float(), nullable=False),
    sa.Column('scheduler_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduler_paused', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('synonyms', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill')
    )
    op.create_table('application_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bullet_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letter_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('merge_fields', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('behavioral_score', sa.Float(), nullable=False),
    sa.Column('behavioral_assessed', sa.Boolean(), nullable=False),
    sa.Column('location_pass', sa.Boolean(), nullable=False),
    sa.Column('location_note', sa.String(), nullable=False),
    sa.Column('career_alignment_score', sa.Float(), nullable=False),
    sa.Column('salary_index', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('gap_keywords', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('resume_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('selected_bullet_ids', sa.JSON(), nullable=False),
    sa.Column('html_path', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('ats_validation', sa.JSON(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_variant_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_variant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_variant_id'], ['cover_letter_variant.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['resume_variant_id'], ['resume_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('resume_variant')
    op.drop_table('evaluation')
    op.drop_table('cover_letter_variant')
    op.drop_table('bullet_library')
    op.drop_table('application_event')
    op.drop_table('skill_bank')
    op.drop_table('settings')
    op.drop_table('qa_bank')
    op.drop_table('job_posting')
    op.drop_table('experience_entry')
    op.drop_table('education_entry')
    op.drop_table('candidate_profile')
    # ### end Alembic commands ###
