"""add application submitted PDF archive paths

Revision ID: 36850bcdc76d
Revises: 9008aea22279
Create Date: 2026-09-14 15:34:28.785109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36850bcdc76d'
down_revision: Union[str, Sequence[str], None] = '9008aea22279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('submitted_resume_path', sa.String(), nullable=False, server_default=''))
    op.add_column('application', sa.Column('submitted_cover_letter_path', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'submitted_cover_letter_path')
    op.drop_column('application', 'submitted_resume_path')
    # ### end Alembic commands ###
