"""add multiuser tables and nullable user_id columns

Revision ID: 514908acd80f
Revises: 10a5627a5d05
Create Date: 2026-09-17 12:57:31.200821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514908acd80f'
down_revision: Union[str, Sequence[str], None] = '10a5627a5d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_candidate_profile_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_candidate_profile_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('education_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_education_entry_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('experience_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_experience_entry_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_job_posting_user_url', ['user_id', 'url'])
        batch_op.create_foreign_key('fk_job_posting_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('qa_bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_qa_bank_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_settings_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_settings_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('skill_bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_skill_bank_user_skill', ['user_id', 'skill'])
        batch_op.create_foreign_key('fk_skill_bank_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Dropping `user_id` alone is sufficient on SQLite: batch mode recreates
    each table from scratch, and every constraint added in `upgrade()`
    (both the named composite-unique ones and the unnamed FK/unique ones)
    references `user_id` -- so none of them survive into the rebuilt table
    once that column is left out. Autogenerate's own unnamed
    `drop_constraint(None, ...)` calls are removed here since they'd raise
    (a constraint can't be dropped by a name that doesn't exist) and are
    redundant with what dropping the column already does.
    """
    with op.batch_alter_table('skill_bank', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('qa_bank', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('experience_entry', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('education_entry', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    op.drop_table('session')
    op.drop_table('user')
