"""drop unused experience_entry.title_tier

Revision ID: 638e4d963ff2
Revises: 14808d7b69a2
Create Date: 2026-09-14 01:00:36.816448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638e4d963ff2'
down_revision: Union[str, Sequence[str], None] = '14808d7b69a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience_entry', 'title_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience_entry', sa.Column('title_tier', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
